---
# tasks for opsatwork.chrony configuration

- name: Copy configuration
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_location }}"
    owner: root
    group: root
    mode: 0664
  notify: restart chrony

- name: Ensure chrony services is started and enabled
  service:
    name: "{{ chrony_service_name }}"
    state: started
    enabled: yes
